import type { TaskFile } from '../types';

/** The prototype stores only a file's name and size, so its content is generated on demand. */

function pdfText(value: string): string {
  // Keep to ASCII so string length matches byte length in the offsets below.
  return value.replace(/[^\x20-\x7E]/g, '?').replace(/([\\()])/g, '\\$1');
}

function samplePdf(title: string, lines: string[]): string {
  const text = [
  'BT',
  '/F1 20 Tf',
  '72 760 Td',
  `(${pdfText(title)}) Tj`,
  '/F1 11 Tf',
  ...lines.map((line, index) => `0 -${index === 0 ? 32 : 18} Td (${pdfText(line)}) Tj`),
  'ET'].
  join('\n');

  const objects = [
  '<< /Type /Catalog /Pages 2 0 R >>',
  '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
  '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>',
  `<< /Length ${text.length} >>\nstream\n${text}\nendstream`,
  '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];


  let pdf = '%PDF-1.4\n';
  const offsets = objects.map((body, index) => {
    const offset = pdf.length;
    pdf += `${index + 1} 0 obj\n${body}\nendobj\n`;
    return offset;
  });
  const xref = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  offsets.forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return pdf;
}

export function isPdf(file: TaskFile): boolean {
  return /\.pdf$/i.test(file.name);
}

/** A stand-in file to preview and download. Only PDFs can be generated; others get a text note. */
export function sampleFile(file: TaskFile, taskName: string): {blob: Blob;downloadName: string;} {
  const lines = [
  `Attached to: ${taskName}`,
  `File size on record: ${file.size}`,
  '',
  'This is sample content generated by the prototype.',
  'The real file will be shown here once uploads are stored.'];

  if (isPdf(file)) {
    return {
      blob: new Blob([samplePdf(file.name, lines)], { type: 'application/pdf' }),
      downloadName: file.name
    };
  }
  return {
    blob: new Blob([[file.name, ...lines].join('\n')], { type: 'text/plain' }),
    downloadName: `${file.name}.txt`
  };
}
